### ISSUE TITLE
♻️ [Refactor] 프론트 로그인 구현 시 백엔드 리팩토링

### ISSUE THREAD

**Issue by whaleshade** [Match-Box-Team/BackEnd#29]
## ♻️ 이슈 체크리스트

- [ ] auth.controller.ts signIn()  리팩토링

## 📄 리팩토링 개요

- auth.controller.ts에서 리다이렉션 프론트와 연동

## 📝 리팩토링 상세 내용

- auth.controller.ts에서 /auth/callback/ 부분에 return을 추가하고 jwt를 발급 해주면서 프론트에서 리다이렉션을 해주도록 함

## ✅ TODO

- [ ] 프론트와 연동
- [ ] jwt 발급 확인
- [ ] return 추가 
- [ ] 리다이렉션 추가

**Comment by Joo-hyun-Kang** [comment]
다음에 하기로 함:)
